---
- hosts: all
  become: True
  become_method: sudo
  tasks:

    - name: Deploy static website
      copy:
        src: index.html # We have define a html page
        dest: /var/www/html/
